name: 'Coding Standard for Magento 2'
description: 'Validates code by PHP Code sniffer'
inputs:
  fileExtensions:
    description: 'File extensions to check'
    required: false
    default: 'php,phtml,xml'
  onlyErrors:
    description: 'Display only errors if such exists'
    required: false
    default: 'no'
  sourceReport:
    description: 'Display Source report if such exists'
    required: false
    default: 'yes'
outputs:
  time:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fileExtensions }}
    - ${{ inputs.onlyErrors }}
    - ${{ inputs.sourceReport }}
branding:
  icon: 'code'
  color: 'green'