name: 'Coding Standard for Magento 2'
description: 'Validates code by PHP Code sniffer'
inputs:
  errorSeverity:
    description: 'Error severity'
    required: false
    default: '8'
  warningSeverity:
    description: 'Warning severity'
    required: false
    default: '8'
outputs:
  time:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.errorSeverity }}
    - ${{ inputs.warningSeverity }}
branding:
  icon: 'code'
  color: 'green'